### You are given two integer arrays, A and B of dimensions NXM.
### Your task is to perform the following operations:
### Add ( A + B)
### Subtract ( A - B)
### Multiply ( A * B)
### Integer Division (A / B)
### Mod (A % B)
### Power (A ** B)

In [3]:
import numpy as np

In [7]:
n, m = map(int, input().split())
a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.floor_divide(a, b))
print(np.mod(a, b))
print(np.power(a, b))

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]
