### In this Eye and Identity problem, Your task is to print an array of size N X M with its main diagonal elements as 1's and 0's everywhere else.

In [10]:
import numpy

In [11]:
n, m = tuple(map(int, input().split()))
print(numpy.eye(n, m))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
