### You are given a 1-D array, A. Your task is to print the floor, celi and rint of all the elements of A.

In [4]:
import numpy as np

In [5]:
np.set_printoptions(sign=' ')

In [6]:
a = np.array(input().split(), float)
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

[  1.   2.   3.   4.  34.  34.]
[  1.   2.   4.   5.  35.  35.]
[  1.   2.   3.   4.  34.  34.]
