### You are given a space separated list of nine integers. Your task is to convert this list into a 3x3 NumPy array.

In [6]:
import numpy as np

In [11]:
my_array = np.array(input().split(' '), int)

 1 2 3 4 5 6 7 8 9


In [13]:
print(np.reshape(my_array, (3, 3))) # or my_array.shape = (3, 3) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
